# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petlist', '0003_auto_20171206_0224'),
        ('comment', '0002_auto_20171206_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentstruct',
            name='pet_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='petlist.Pets'),
        ),
        migrations.AlterField(
            model_name='commentstruct',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
