# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('pet_id', models.ForeignKey(default='0', on_delete=id, to='petlist.Pets')),
                ('user_id', models.ForeignKey(default='0', on_delete=id, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
