# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='0')),
                ('pet_id', models.IntegerField(default='0')),
                ('vote', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='petvote',
            unique_together=set([('user_id', 'pet_id')]),
        ),
    ]
