# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petlist', '0001_initial'),
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVote',
            new_name='PetVote',
        ),
        migrations.AlterUniqueTogether(
            name='petvote',
            unique_together=set([('user_id', 'pet_id')]),
        ),
    ]
