# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0004_auto_20171202_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='petvote',
            unique_together=set([('user_id', 'pet_id')]),
        ),
    ]
