# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0002_auto_20171202_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petvote',
            name='pet_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='petvote',
            name='user_id',
            field=models.IntegerField(default='0'),
        ),
    ]
