# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0003_auto_20171202_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='petvote',
            unique_together=set([]),
        ),
    ]
