# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowStruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default='0')),
                ('follow_id', models.IntegerField(default='0')),
                ('following', models.BooleanField(default='False')),
            ],
        ),
    ]
