# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pet_photo2',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pets',
            name='pet_photo3',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pets',
            name='pet_photo4',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pets',
            name='pet_photo5',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pets',
            name='pet_photo6',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_photo',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
    ]
